name: Run clang-format Linter

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.12
      with:
        source: '.'
        extensions: 'h,cpp,c'
        clangFormatVersion: 12
        inplace: True
    - uses: EndBug/add-and-commit@v4
      with:
        author_name: Github Action Robot
        author_email: robot@github.com
        message: 'Committing clang-format changes'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
